name: Build IPA for Sideloading

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - uses: actions/checkout@v4 

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 

      - name: Install Node.js Dependencies
        run: npm install

      - name: Copy Web Assets (Capacitor Sync)
        run: npx cap copy ios
        
      - name: Install Pods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Build the IPA 
        run: |
          # Archive the project (FINAL CODE SIGNING FIX)
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean archive
          
          # Export the .ipa file
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ios/App/App/Info.plist \
            -allowProvisioningUpdates

      - name: Upload the .ipa file
        uses: actions/upload-artifact@v4
        with:
          name: Musi-App-IPA
          path: build/App.ipa
