name: Build IPA for Sideloading

on:
  workflow_dispatch: # This lets you click a button to start the build

jobs:
  build:
    runs-on: macos-latest # This requests a free Mac virtual machine

    steps:
      - uses: actions/checkout@v4 # Get your code

      - name: Install Dependencies
        run: npm install

      - name: Copy Web Assets (Safety Check)
        run: npx cap copy ios

      - name: Build the IPA 
        run: |
          # Archive the project (Corrected path for the .xcodeproj file)
          xcodebuild -project ios/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            clean archive
          
          # Export the .ipa file (Corrected path for Info.plist)
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ios/App/Info.plist \
            -allowProvisioningUpdates
      - name: Upload the .ipa file
        uses: actions/upload-artifact@v4
        with:
          name: Musi-App-IPA
          path: build/App.ipa
