name: Build IPA for Sideloading

on:
  # This lets you click a button to start the build manually from the Actions tab
  workflow_dispatch: 

jobs:
  build:
    # This requests a free Mac virtual machine
    runs-on: macos-latest 

    steps:
      - uses: actions/checkout@v4 # Get your code

      - name: Install Dependencies
        run: npm install

      - name: Copy Web Assets (Safety Check)
        run: npx cap copy ios
        
      # CRITICAL FIX: Install and Update CocoaPods Dependencies
      - name: Install Pods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Build the IPA 
        run: |
          # Archive the project (CORRECTED PATH)
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            clean archive
          
          # Export the .ipa file (CORRECTED Info.plist PATH)
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ios/App/App/Info.plist \
            -allowProvisioningUpdates

      - name: Upload the .ipa file
        uses: actions/upload-artifact@v4
        with:
          name: Musi-App-IPA
          path: build/App.ipa
