name: Build IPA for Sideloading

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - uses: actions/checkout@v4 

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 

      - name: Install Node.js Dependencies
        run: npm install

      - name: Copy Web Assets (Capacitor Sync)
        run: npx cap copy ios
        
      - name: Install Pods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Build and Export Unsigned IPA (Supported Method Fix)
        run: |
          # 1. Archive the project, explicitly disabling code signing. (This step SUCCEEDS)
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean archive
          
          # 2. Create ExportOptions.plist using the *supported* method: 'development'.
          # We eliminate all other keys to avoid validation errors.
          cat << EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
          </dict>
          </plist>
          EOF
          
          # 3. Export the .ipa file.
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload the .ipa file
        uses: actions/upload-artifact@v4
        with:
          name: Musi-App-IPA
          path: build/App.ipa
